### ISSUE TITLE
ItemsMixin will break compatibility with special tools from other mods

### ISSUE THREAD

**Issue by CammiePone** [rizecookey/CombatEdit#1]
So a friend and I were taking a look at your code, and we noticed ItemsMixin was a bit... unsafe. It assumes all tools, even modded ones, never make their own custom class extending their desired tool class. The problem with that is that it will inherently break any mods, like Botania and Bewitchment, that need to make their own specialized tool classes.

**Comment by rizecookey** [comment]
Should be fixed in version 1.3.0 (https://github.com/rizecookey/CombatEdit/releases/tag/v1.3.0-1.16) (see https://github.com/rizecookey/CombatEdit/commit/bc4207654d9eaea56ae15ab809046bc41ae550d0).
