### ISSUE TITLE
When going into a world that was created without combatedit mod, it just has hand cooldown.

### ISSUE THREAD

**Issue by DanielMC101** [rizecookey/CombatEdit#14]
So basically, if you created a world before you had the mod on, it will have player hand cooldown when you're holding any weapons and tools. But if you basically die in the world, it will have no cooldown

https://github.com/rizecookey/CombatEdit/assets/39068731/a617cb4a-6d55-48b3-abb3-1a0d8936b959

**Comment by rizecookey** [comment]
This should be fixed with release [1.6.5](https://github.com/rizecookey/CombatEdit/releases/tag/v1.6.5), thank you for reporting the bug!

**Comment by DanielMC101** [comment]
@rizecookey thanks! And btw, in case u didn't notice, ur mod has been included in the modpack called re-console, and in fact I think ur mod is the best for making combat be like Legacy console edition, btw it would be very nice if u were to add an option to make damage tooltip display like in legacy console edition like blue text, and display the .0 on the hotbar, or I was really thinking of maybe forking ur mod to do this, but I have no clue how to do this as I don't really know how to program.
