### ISSUE TITLE
installing this mod on server, it shows hand cooldown.

### ISSUE THREAD

**Issue by DanielMC101** [rizecookey/CombatEdit#15]
https://github.com/rizecookey/CombatEdit/assets/39068731/49c25e02-45ae-40f8-bea1-e261cb1d4d8f

**Comment by rizecookey** [comment]
This should be fixed with release [1.6.5](https://github.com/rizecookey/CombatEdit/releases/tag/v1.6.5), thank you for reporting the bug!
