### ISSUE TITLE
Config doesn't work on mod menu

### ISSUE THREAD

**Issue by DanielMC101** [rizecookey/CombatEdit#18]
![2024-09-25_16 24 11](https://github.com/user-attachments/assets/f8cd7cd0-d996-4a64-84ae-cb9d975222ac)

**Comment by rizecookey** [comment]
I've removed release 2.0 for now as it has a few issues, including it not being bundled with the config library required for the config screen.

**Comment by rizecookey** [comment]
Fixed in [2.0.1](https://github.com/rizecookey/CombatEdit/releases/tag/v2.0.1%2B1.20.6), thanks for reporting!
