### ISSUE TITLE
Crashes with Legacy4J mod when creating, or loading a world.

### ISSUE THREAD

**Issue by DanielMC101** [rizecookey/CombatEdit#19]
https://mclo.gs/6cym5QH

**Comment by rizecookey** [comment]
Fixed in release [2.0.4](https://github.com/rizecookey/CombatEdit/releases/tag/v2.0.4%2B1.21.1), thanks for reporting!

**Comment by DanielMC101** [comment]
@rizecookey nice, can you also add an option to disable "When on main hand" and "When on body, etc" for armors?

**Comment by DanielMC101** [comment]
@rizecookey also, do u have discord so that i can contact u?
