### ISSUE TITLE
CombatEdit raises the attack damage of SwordItem if lowered with a custom class

### ISSUE THREAD

**Issue by CammiePone** [rizecookey/CombatEdit#2]
This probably affects all tools, but testing with [Antrhopophagy](https://github.com/MoriyaShiine/anthropophagy), the knives (whose damage is [set here](https://github.com/MoriyaShiine/anthropophagy/blob/master/src/main/java/moriyashiine/anthropophagy/common/item/KnifeItem.java)) gets raised by 4 attack damage.

With CombatEdit:
![image](https://user-images.githubusercontent.com/16853086/104489921-322dfb00-559e-11eb-805f-892eb464fd36.png)

Without CombatEdit:
![image](https://user-images.githubusercontent.com/16853086/104490069-63a6c680-559e-11eb-999a-fbf3296c8630.png)

**Comment by rizecookey** [comment]
Should be fixed with [this commit](https://github.com/rizecookey/CombatEdit/commit/5b6cfe6364f81ca9ecdc1b2d841836f41e6bbdcc) in release [1.3.2](https://github.com/rizecookey/CombatEdit/releases/tag/v1.3.2-1.16).
