### ISSUE TITLE
<Suggestion> 1.21.4 port?

### ISSUE THREAD

**Issue by DanielMC101** [rizecookey/CombatEdit#23]
Any plans for this?

**Comment by rizecookey** [comment]
I've just released a [port for 1.21.4](https://github.com/rizecookey/CombatEdit/releases/tag/v2.0.5%2B1.21.4).

**Comment by DanielMC101** [comment]
@rizecookey yoo thank you so much man, and btw just wanna ask can you maybe add an option to hide the "when on main hand" "when on body" etc?
