### ISSUE TITLE
Modded weapons that don't use a vanilla class have their attack damage set to 1

### ISSUE THREAD

**Issue by MoriyaShiine** [rizecookey/CombatEdit#3]
Shown here with multiple mods

![image](https://user-images.githubusercontent.com/45156123/116430287-51c6f780-a80c-11eb-81d7-ab0c1b96342e.png)
![image](https://user-images.githubusercontent.com/45156123/116430309-57244200-a80c-11eb-83dc-b2716cce8d3e.png)
![image](https://user-images.githubusercontent.com/45156123/116430328-5be8f600-a80c-11eb-9fd7-13c41871ddf5.png)
![image](https://user-images.githubusercontent.com/45156123/116430350-60adaa00-a80c-11eb-9b6a-eb004ac08a52.png)

However Chest Cavity's Cleavers work fine because they use the vanilla SwordItem class
![image](https://user-images.githubusercontent.com/45156123/116430440-7622d400-a80c-11eb-926c-02c7a23f3792.png)

**Comment by rizecookey** [comment]
Fixed in version [1.3.3](https://github.com/rizecookey/CombatEdit/releases/tag/v1.3.3-1.16), thank you for the bug report!
