### ISSUE TITLE
1.18

### ISSUE THREAD

**Issue by cootshk** [rizecookey/CombatEdit#7]
Is there an estimated 1.18 release? (I am trying to use this with Geyser Fabric, and Bedrock clients use 1.8 pvp.)

**Comment by rizecookey** [comment]
Just released [v0.1.5](https://github.com/rizecookey/CombatEdit/releases/tag/v1.5.0). From my testing it seemed like I didn't have to change much to make it work, but if you find any bugs, please let me know.
